tap "hashicorp/tap"

brew "git"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "python@3.13"
brew "gh"
brew "copilot"
brew "glab"
brew "pre-commit"
brew "hashicorp/tap/terraform"
brew "terraform-docs"
brew "openjdk@11"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "hatch"


cask "git-credential-manager"
cask "google-chrome"
cask "iterm2"
cask "pycharm"
cask "intellij-idea"
cask "alfred"
cask "chatgpt"

